url: https://giadatanghetti.it/
baseurl: ""

# Site settings
title: Giada Tanghetti - Musicoterapeuta, Educatrice & Cantante
email: tanghettigiada@gmail.com
description: "Giada Tanghetti - Musicoterapeuta, Educatrice & Cantante. Opera in provincia di Brescia, sul lago di Garda (Salò). Attualmente educatrice presso la scuola dell'infanzia \"Mariuccia Castellani\" di Montegargnano."
keywords: giada, tanghetti, musicoterapia, propedeutica, educazione, infanzia, asilo, musicoterapeuta, canto, cantante, salò, brescia, garda, lago

# Postal address (add as many lines as necessary)
address:
  - line: Centro FA.BA
  - line: Via Enrico Fermi 5A
  - line: Cunettone (Salò), 25087, Brescia, Italia

# Build settings
markdown: kramdown
permalink: pretty
